export const coursePageData = {
  java: {
    badge: "Programming Track",
    title: "Java Programming Course",
    shortTitle: "Java Essentials",
    thumbnailLabel: "JAVA",
    thumbnailCopy: "Clean fundamentals, OOP thinking, and problem-solving practice for semester learning and placements.",
    summary:
      "Start with syntax and build up to functions, arrays, strings, and logic-building patterns through one structured Java journey.",
    palette: {
      primary: "#0f4c81",
      soft: "rgba(15, 76, 129, 0.12)",
      ink: "#0d223a",
    },
    oneShot: {
      title: "Java Tutorial for Beginners | Learn Java in 2 Hours",
      channel: "Apna College",
      duration: "2 hours",
      url: "https://www.youtube.com/watch?v=UmnCZ7-9yDY",
    },
    outcomes: ["Syntax to logic", "Placement basics", "OOP foundation"],
    topics: [
      { title: "Java setup and syntax", desc: "Create files, understand boilerplate code, and run your first Java program." },
      { title: "Variables and data types", desc: "Use primitive types, input handling, and type conversion with confidence." },
      { title: "Operators and conditionals", desc: "Write decision-making logic using operators, if-else, ternary, and switch." },
      { title: "Loops and pattern logic", desc: "Practice while, for, do-while, break, and continue through core problems." },
      { title: "Functions and methods", desc: "Understand method structure, parameters, overloading, and scope." },
      { title: "Arrays and searching", desc: "Cover arrays, input-output updates, and common search-based questions." },
      { title: "Strings and builders", desc: "Work with immutable strings, input handling, and StringBuilder patterns." },
      { title: "Practice questions", desc: "Apply concepts on factorials, prime ranges, reverse-number, and similar exercises." },
    ],
  },
  dsa: {
    badge: "Interview Prep Track",
    title: "Data Structures and Algorithms",
    shortTitle: "DSA Roadmap",
    thumbnailLabel: "DSA",
    thumbnailCopy: "Core problem-solving structures organized into an easier revision flow for practice and interviews.",
    summary:
      "Move from lists and stacks to trees, hashing, and graphs with a clearer DSA path and one full resource to revise from.",
    palette: {
      primary: "#7c3aed",
      soft: "rgba(124, 58, 237, 0.12)",
      ink: "#24163f",
    },
    oneShot: {
      title: "DSA Full Course 2025 | Data Structures and Algorithms Tutorial",
      channel: "Simplilearn",
      duration: "Full course",
      url: "https://www.youtube.com/live/x4S6pzVFwEQ",
    },
    outcomes: ["Problem solving", "Interview topics", "Revision ready"],
    topics: [
      { title: "ArrayList and linked lists", desc: "Understand dynamic collections and linked list operations from scratch." },
      { title: "Stacks and queues", desc: "Learn stack logic, queue variants, and implementation strategies." },
      { title: "Binary trees and BST", desc: "Build tree intuition with traversals, search, height, and delete operations." },
      { title: "Hashing and maps", desc: "Use HashMap, LinkedHashMap, TreeMap, and set-based patterns effectively." },
      { title: "Graphs and representation", desc: "Represent graphs cleanly and move into BFS, DFS, and path questions." },
      { title: "Traversal patterns", desc: "Practice preorder, postorder, breadth-first, and depth-first thinking." },
      { title: "Popular coding questions", desc: "Revisit distinct elements, valid anagram, and root-to-leaf style problems." },
      { title: "Placement revision", desc: "Group high-frequency structures for mock-test and interview preparation." },
    ],
  },
  advJava: {
    badge: "Programming Track",
    title: "Advanced Java Course",
    shortTitle: "Advanced Java",
    thumbnailLabel: "ADV JAVA",
    thumbnailCopy: "A simpler guide to enterprise Java concepts used in backend development and project work.",
    summary:
      "Advance beyond syntax into JDBC, JSP, servlets, Java APIs, and modern backend-oriented Java development topics.",
    palette: {
      primary: "#166534",
      soft: "rgba(22, 101, 52, 0.12)",
      ink: "#13291a",
    },
    oneShot: {
      title: "Advanced Java Full Course in 11 Hours",
      channel: "Genie Ashwani",
      duration: "11 hours",
      url: "https://www.youtube.com/watch?v=QHWZcrYLV0g",
    },
    outcomes: ["JDBC basics", "Web Java flow", "Project-ready concepts"],
    topics: [
      { title: "JDBC and database connectivity", desc: "Connect Java applications with relational databases using JDBC patterns." },
      { title: "Servlet lifecycle", desc: "Understand request handling, response writing, and server-side Java flow." },
      { title: "JSP fundamentals", desc: "Render dynamic views and connect backend logic to front-end pages." },
      { title: "Session and cookies", desc: "Track users and state in Java web applications." },
      { title: "MVC approach", desc: "Organize advanced Java applications with cleaner structure and separation." },
      { title: "Spring Boot introduction", desc: "Get an entry point into modern Java backend development." },
    ],
  },
  html: {
    badge: "Full Stack Foundations",
    title: "HTML Course",
    shortTitle: "HTML Basics",
    thumbnailLabel: "HTML",
    thumbnailCopy: "Simple page structure, semantic tags, and form-building essentials for every web learner.",
    summary:
      "Cover the complete HTML foundation with a single beginner-friendly resource and a clean map of the topics that matter most.",
    palette: {
      primary: "#ea580c",
      soft: "rgba(234, 88, 12, 0.12)",
      ink: "#3a1f11",
    },
    oneShot: {
      title: "HTML Tutorial for Beginners in Hindi with Notes",
      channel: "CodeWithHarry",
      duration: "1 video",
      url: "https://www.youtube.com/watch?v=BsDoLVMnmZs",
    },
    outcomes: ["Web structure", "Semantic markup", "Form basics"],
    topics: [
      { title: "Document structure", desc: "Understand tags, metadata, layout scaffolding, and the HTML document shell." },
      { title: "Text and media tags", desc: "Use headings, paragraphs, images, audio, and video elements correctly." },
      { title: "Links and navigation", desc: "Connect pages and structure navigation with semantic anchors." },
      { title: "Lists and tables", desc: "Present grouped content and tabular information in a clean way." },
      { title: "Forms and inputs", desc: "Build input-driven pages using forms, labels, validation, and field types." },
      { title: "Semantic HTML", desc: "Use sectioning tags that improve readability, SEO, and accessibility." },
    ],
  },
  css: {
    badge: "Full Stack Foundations",
    title: "CSS Course",
    shortTitle: "CSS Styling",
    thumbnailLabel: "CSS",
    thumbnailCopy: "Layout, spacing, and visual polish taught through a more minimal and easier-to-follow study plan.",
    summary:
      "Learn how to turn plain HTML into polished interfaces using selectors, spacing, layouts, responsiveness, and effects.",
    palette: {
      primary: "#2563eb",
      soft: "rgba(37, 99, 235, 0.12)",
      ink: "#112440",
    },
    oneShot: {
      title: "CSS 3 Tutorial for Beginners | Learn CSS in One Video in Hindi",
      channel: "CodeWithHarry",
      duration: "1 video",
      url: "https://www.youtube.com/watch?v=u5-K_ua9sOw",
    },
    outcomes: ["UI styling", "Responsive basics", "Modern layouts"],
    topics: [
      { title: "Selectors and specificity", desc: "Target elements correctly and understand styling priority." },
      { title: "Box model and spacing", desc: "Work with margin, padding, borders, and content sizing." },
      { title: "Typography and colors", desc: "Create readable, balanced interfaces with text and palette choices." },
      { title: "Flexbox and grid", desc: "Build layouts that adapt cleanly across sections and screens." },
      { title: "Responsive design", desc: "Use breakpoints and fluid sizing to support mobile-first layouts." },
      { title: "Transitions and polish", desc: "Add interaction states, hover feedback, and soft motion thoughtfully." },
    ],
  },
  javascript: {
    badge: "Full Stack Foundations",
    title: "JavaScript Course",
    shortTitle: "JavaScript Logic",
    thumbnailLabel: "JAVASCRIPT",
    thumbnailCopy: "Core language concepts, DOM work, and logic building collected into one cleaner subject experience.",
    summary:
      "Build a strong JavaScript base covering data types, control flow, arrays, objects, loops, and browser-side programming.",
    palette: {
      primary: "#ca8a04",
      soft: "rgba(202, 138, 4, 0.14)",
      ink: "#3b2a10",
    },
    oneShot: {
      title: "JavaScript Full Course 2024 | JavaScript Tutorial for Beginners",
      channel: "Simplilearn",
      duration: "Full course",
      url: "https://www.youtube.com/watch?v=Q4p8vRQX8uY",
    },
    outcomes: ["Language basics", "DOM understanding", "Frontend logic"],
    topics: [
      { title: "Variables and data types", desc: "Understand primitives, variables, operators, and common value handling." },
      { title: "Conditionals and loops", desc: "Build control flow using if-else, switch, while, for, and loop patterns." },
      { title: "Strings and arrays", desc: "Use methods, slicing, splicing, nested arrays, and iteration techniques." },
      { title: "Functions and scope", desc: "Write reusable logic and understand how values flow through functions." },
      { title: "Objects and references", desc: "Work with structured data and references in practical ways." },
      { title: "DOM-ready mindset", desc: "Prepare for browser interaction, dynamic rendering, and frontend behavior." },
      { title: "ES6+ patterns", desc: "Revisit template literals and modern JavaScript habits used in projects." },
      { title: "Logic-building exercises", desc: "Practice the question styles that support coding rounds and interviews." },
    ],
  },
  react: {
    badge: "MERN / Full Stack Track",
    title: "React JS Course",
    shortTitle: "React UI",
    thumbnailLabel: "REACT",
    thumbnailCopy: "Component-based UI learning with a calmer visual structure and one-shot revision support.",
    summary:
      "Learn React through components, JSX, props, hooks, and state-driven UI building with a resource that is easy to revisit.",
    palette: {
      primary: "#0891b2",
      soft: "rgba(8, 145, 178, 0.12)",
      ink: "#102a33",
    },
    oneShot: {
      title: "React JS in One Shot | React JS Full Course 2026",
      channel: "Aryan Singh",
      duration: "1 video",
      url: "https://www.youtube.com/watch?v=vHHporUrDtM",
    },
    outcomes: ["Components", "Hooks", "Reusable UI"],
    topics: [
      { title: "What is React and JSX", desc: "Start with the React model and understand how JSX shapes component output." },
      { title: "Local setup and project flow", desc: "Set up the environment and understand file structure clearly." },
      { title: "Components and props", desc: "Pass data cleanly and break interfaces into reusable pieces." },
      { title: "State and hooks", desc: "Use useState and related hooks to build dynamic user experiences." },
      { title: "Event handling", desc: "Respond to clicks, inputs, and interactive behavior with confidence." },
      { title: "Conditional rendering", desc: "Switch UI paths based on values, state, and user context." },
      { title: "Dynamic styling", desc: "Apply class changes and style logic without losing clarity." },
      { title: "Project-ready thinking", desc: "Move from examples to structure that works in larger React apps." },
    ],
  },
  nodejs: {
    badge: "Backend Track",
    title: "Node JS Course",
    shortTitle: "Node Runtime",
    thumbnailLabel: "NODE",
    thumbnailCopy: "Backend learning made cleaner with a quick one-shot and a sober topic map for revision.",
    summary:
      "Understand the Node.js runtime, npm workflow, modules, environment handling, and the foundations of backend JavaScript.",
    palette: {
      primary: "#15803d",
      soft: "rgba(21, 128, 61, 0.12)",
      ink: "#132b1b",
    },
    oneShot: {
      title: "Complete Backend One Shot | NodeJs, ExpressJs, MongoDB",
      channel: "Sheryians Coding School",
      duration: "1 video",
      url: "https://www.youtube.com/watch?v=0IciwnJ6PJI",
    },
    outcomes: ["Node basics", "npm workflow", "Backend setup"],
    topics: [
      { title: "What is Node.js", desc: "Understand why Node exists and where it fits in modern web development." },
      { title: "Node installation and REPL", desc: "Set up the runtime and explore commands using the REPL environment." },
      { title: "Modules and exports", desc: "Split logic across files and import modules the right way." },
      { title: "Process and environment", desc: "Work with process information and environment-oriented backend behavior." },
      { title: "npm and packages", desc: "Use npm, install packages, and understand package.json structure." },
      { title: "Project initialization", desc: "Set up backend projects in a way that scales into real Express apps." },
    ],
  },
  express: {
    badge: "Backend Track",
    title: "Express JS Course",
    shortTitle: "Express APIs",
    thumbnailLabel: "EXPRESS",
    thumbnailCopy: "Routing and server-side request handling explained in a more polished, low-noise course layout.",
    summary:
      "Learn how to build Express applications, create routes, handle requests, and structure backend APIs more clearly.",
    palette: {
      primary: "#374151",
      soft: "rgba(55, 65, 81, 0.12)",
      ink: "#111827",
    },
    oneShot: {
      title: "Complete Backend One Shot | NodeJs, ExpressJs, MongoDB",
      channel: "Sheryians Coding School",
      duration: "1 video",
      url: "https://www.youtube.com/watch?v=0IciwnJ6PJI",
    },
    outcomes: ["Express routing", "API basics", "Request handling"],
    topics: [
      { title: "Express app setup", desc: "Create your first Express server and understand the application object." },
      { title: "Routing fundamentals", desc: "Map URLs to controller logic with cleaner route definitions." },
      { title: "Request and response cycle", desc: "Handle request data and shape the right responses." },
      { title: "Path and query parameters", desc: "Extract dynamic values from URLs and query strings." },
      { title: "Middleware mindset", desc: "Understand how Express chains logic and request processing." },
      { title: "REST structure", desc: "Prepare for backend API building using real-world route organization." },
    ],
  },
  mongodb: {
    badge: "Backend Track",
    title: "MongoDB Course",
    shortTitle: "MongoDB Data",
    thumbnailLabel: "MONGODB",
    thumbnailCopy: "Database concepts organized with clearer topic grouping and a single direct video resource.",
    summary:
      "Move through MongoDB shell basics, collections, CRUD, and Mongoose integration using a simpler study-first layout.",
    palette: {
      primary: "#047857",
      soft: "rgba(4, 120, 87, 0.12)",
      ink: "#102621",
    },
    oneShot: {
      title: "Complete Backend One Shot | NodeJs, ExpressJs, MongoDB",
      channel: "Sheryians Coding School",
      duration: "1 video",
      url: "https://www.youtube.com/watch?v=0IciwnJ6PJI",
    },
    outcomes: ["CRUD basics", "Mongoose intro", "Backend data flow"],
    topics: [
      { title: "Mongo shell basics", desc: "Start with collections, documents, and shell-based exploration." },
      { title: "Insert and find operations", desc: "Create and retrieve documents using the most common CRUD flows." },
      { title: "Update and delete patterns", desc: "Modify and remove data cleanly while understanding query behavior." },
      { title: "Mongoose introduction", desc: "Connect MongoDB to Node applications through Mongoose." },
      { title: "Schemas and models", desc: "Design data shapes and interact through model-based logic." },
      { title: "Validation and schema options", desc: "Improve data quality with useful schema rules and options." },
    ],
  },
  mysql: {
    badge: "Database Track",
    title: "MySQL Course",
    shortTitle: "MySQL Queries",
    thumbnailLabel: "MYSQL",
    thumbnailCopy: "SQL concepts reduced into a more focused revision-first layout with a direct one-shot resource.",
    summary:
      "Learn relational database basics and SQL query writing with a single MySQL resource that is easier to revisit before exams and interviews.",
    palette: {
      primary: "#1d4ed8",
      soft: "rgba(29, 78, 216, 0.12)",
      ink: "#102449",
    },
    oneShot: {
      title: "SQL Complete Course in 3 Hours | SQL One Shot using MySQL",
      channel: "Apna College",
      duration: "3 hours",
      url: "https://www.youtube.com/live/hlGoQC332VM",
    },
    outcomes: ["SQL syntax", "Database logic", "Interview revision"],
    topics: [
      { title: "Database and table setup", desc: "Understand how to create and organize structured relational data." },
      { title: "CRUD queries", desc: "Insert, select, update, and delete records with clarity." },
      { title: "Filtering and sorting", desc: "Use WHERE, ORDER BY, and limits for result shaping." },
      { title: "Aggregate functions", desc: "Summarize data using count, sum, average, and grouped queries." },
      { title: "Joins and relationships", desc: "Connect related tables using practical join logic." },
      { title: "Schema design basics", desc: "Think through naming, normalization, and database-ready data models." },
    ],
  },
};
